// <auto-generated />
namespace _2001216310_NguyenThanhVi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class UDPro : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UDPro));
        
        string IMigrationMetadata.Id
        {
            get { return "202311271406523_UDPro"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
